### ISSUE TITLE
의존관계 검색과 주입의 차이점 

### ISSUE THREAD

**Issue by kyuuuunmi** [study-toby-spring/yuuuuunmi.ko#3]
**의존관계 검색** 방식에서는 검색하는 오브젝트는 자신이 스프링의 빈일 필요가 없다. 단지 주입 대상만 빈이기만 하면 된다.
**의존관계 주입** 방식에서는 주입 주체와 주입 대상 둘다 스프링의 빈이어야 한다. 

검색은 직접 정해놓은 이름을 전달해서 능동적으로 찾는 것이기 때문에 따로 등록이 필요하지 않은 것인가?-?

**Comment by XDXO** [comment]
내가 이해하는 바로는 코드를 생각하면 조금 이해가 편한데 ..

검색은 `ApplicationContext`에서 가져올 수 있는 타입을 기반으로 가져오는데 비해서
주입은 `XML` 설정이나 `@Config` 파일 안에서 설정을 미리 해야하는 차이가 있는 듯 ? (P. 117~8)

```xml
<beans ...>
    <bean id="a" class="...">
        <property name="b" ref="x"
    </bean>
    <bean id="x" class="..."/>
</beans>
```

위는 주입 예제인데, id가 a인 객체를 생성하기 위해서 x를 필요로 하기 때문에 빈에 등록되어 있어야 하는데

```java
public class UserDao {

    private ConnectionMaker connectionMaker;

    public UserDao() {
        AnnotationConfigApplicationContext = context = new AnnotationConfigApplicationContext(DaoFactory.class);
        this.connectionMaker = context.Bean("connectionMaker", ConnectionMaker.class);
    }
}
```

여기서 `this.connectionMaker`는 컨텍스트에서 `ConnectionMaker` 객체를 가져와서 할당할 뿐이지 `UserDao` 자체가 등록될 필요는 없는게 큰 차이점인듯 ?

결론적으로는 검색이 조금 더 포괄적인 개념이긴 한데 코드에 `AnnotationConfigApplicationContext`처럼 스프링 코드가 섞이니깐 어지간하면 의존관계 주입으로 해결하라는게 책의 포인트인듯

**Comment by kyuuuunmi** [comment]
예제까지 감사합니다! :D
