### ISSUE TITLE
xml 프로퍼티 값 주입시 value 선언

### ISSUE THREAD

**Issue by kyuuuunmi** [study-toby-spring/yuuuuunmi.ko#4]
xml 프로퍼티 값 주입시, value값을 xml명시하지 않고 다른 파일에서 상수로 정의하여 가져 올 방법은 없을까~

**Comment by noep** [comment]
propertyplaceholderconfigurer로 검색하면 자료가 많이 나옵니다
http://springsource.tistory.com/m/106

**Comment by kyuuuunmi** [comment]
해결했습니다 감사합니다 :D

**Comment by kyuuuunmi** [comment]
해결했습니다 감사합니다 :D
