### ISSUE TITLE
스프링 테스트 컨텍스트 테스트

### ISSUE THREAD

**Issue by kyuuuunmi** [study-toby-spring/yuuuuunmi.ko#5]
> (p.202~p.204) 

다수의 어플리케이션 컨텍스트 파일이 있을 때, `@ContextConfiguration`어노테이션의 `location`을 지정해 주면 원하는 컨텍스트를 선택 할 수 있다. 
하지만 아래의 경우, 어떻게 원하는 컨텍스트 파일을 주입하는가? 

```java 
... 
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration
public class JUnitTest {
    @Autowired
    ApplicationContext context;

    ...
}
```

어떤 어플리케이션 컨텍스트를 선택할지 어디에 명시를 해주었는가? 해주지 않는다면 어떤 기준으로 찾아가는가..!

**Comment by XDXO** [comment]
나중에 언급되는데 별도로 파일 설정을 안할 경우는 *-context.xml 파일을 자동으로 찾아 주입합니다 (p. 452)
